{
    "openapi": "3.0.0",
    "info": {
        "title": "QuickBank",
        "description": "API Integrações QuickBank",
        "version": "1.0.0"
    },
    
    "paths":{
        "/login/": {
            "post":{
                "description":"teste",
                "tags":["Login"],
                "requestBody": {
                    "content":{
                        "application/json":{
                            "schema":{
                               "$ref": "#/components/schemas/login"
                            },
                            "examples":{
                                "Transferencia":{
                                    "value":{
                                        "usuario": "@userteste",
                                        "senha": "Teste2342@@R"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Result",
                        "content": {
                            "application/json" : {
                                "schema": {
                                    "oneOf": {
                                        "$ref": "#/components/schemas/loginError"
                                    },
                                "examples":{
                                    "error":{
                                        "summary": "Erro",
                                        "value":{
                                            "errorCode": "00002",
                                            "errorMsg": "O usuário inicial não pode ser o mesmo de destino, favor verificar o dado digitado !"
                                        }
                                    }
                                }
                              }
                            }
                         
                        }
                        
                    },
                    "200": {
                        "description" : "Transferência efetuada com sucesso"
                    }
                }
            }
        },
        "/password/ResetPassword" : {
            "post" : {
                "description" : "Gera o reset de senha do usuário e envia o e-mail com o link de redefinição",
                "tags" : ["Password"],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema":{
                                "$ref": "#/components/schemas/ResetPassword"
                             }
                        },
                        "examples":{
                            "ResetPassword":{
                                "value":{
                                    "user": "userTeste"
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "200": {
                        "description": "true"
                    },
                    "400":{
                        "description": "Usuário inexistente !"
                    }
                }
            }
        },
        "/password/NewPassword" : {
            "post" : {
                "description" : "Gera a nova senha do usuário",
                "tags" : ["Password"],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema":{
                                "$ref": "#/components/schemas/NewPassword"
                             }
                        },
                        "examples":{
                            "ResetPassword":{
                                "value":{
                                    "email" : "email@gmail.com",
                                    "senha" : "4578451@Fg",
                                    "token" : "6a5ae858c38c6fea58cc17ab0fed60d1d779930c"
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "200": {
                        "description": "Senha Alterada Com Sucesso !"
                    },
                    "400":{
                        "description": "Token expirado !"
                    }
                }
            }
        },
        "/saldo/Transfer":{
            "put":{
                "description":"teste",
                "tags":["Transfer"],
                "security": [ {"bearerAuth": [] }],
                "requestBody": {
                    "content":{
                        "application/json":{
                            "schema":{
                               "$ref": "#/components/schemas/Transferencia"
                            },
                            "examples":{
                                "Transferencia":{
                                    "value":{
                                        "conta": "307486",
                                        "contaDestino": "307485",
                                        "valor": "75.90"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorizes"
                    },
                    "400":{
                        "description": "O usuário inicial não pode ser o mesmo de destino, favor verificar o dado digitado !"
                    },
                    "200": {
                        "description" : "Transferência efetuada com sucesso"
                    }
                }
            }
        },
        "/accounts/GetUserFilterName/{filterName}": {
            "get": {
                "description": "Busca de usuário por filterName",
                "tags": ["Accounts"],
                "security": [ {"bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "filterName",
                        "in": "path",
                        "description": "FilterName do usuário",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Usuário inexistente !"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/accounts/NewUser" : {
            "post" : {
                "description": "Cria um novo usuário",
                "tags": ["Accounts"],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref": "#/components/schemas/NewAccount"
                            }
                        },
                        "examples":{
                            "NewAccount":{
                                "value":{
                                    "name": "Bruno Freitas",
                                    "userFilter" : "brunofreitas",
                                    "senha": "afsawqs@12376",
                                    "cpf" : "07799309083",
                                    "email" : "bruno@gmail.com"
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "400":{
                        "description": "Usuário já existente"
                    },
                    "200": {
                        "description" : "OK"
                    }
                }
            }
        },
        "/expenses/NewExpense":{
            "post":{
                "description": "Adicionar uma expense positiva ou negativa ao usuário",
                "tags":["Expenses"],
                "security": [ {"bearerAuth": [] }],
                "requestBody": {
                    "content":{
                        "application/json":{
                            "schema":{
                               "$ref": "#/components/schemas/NewExpense"
                            },
                            "examples":{
                                "Transferencia":{
                                    "value":{
                                        "parentId": "5f5d2dfdb2f39e0c743163a9",
	                                    "parentName" : "Bruno Freitas",
	                                    "valor" : -100,
	                                    "data" : "01/09/2021 11:30:00",
	                                    "categoria": "Compras",
	                                    "descricao": "Supermercado"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Usuário não encontrado na base de dados"
                    }
                }
            }
        },
        "/expenses/{userId}": {
            "get": {
                "description": "Busca a lista de expenses do usuário",
                "tags": ["Expenses"],
                "security": [ {"bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Nenhuma expense encontrada !"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ListExpenses"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/goals/UpdateTargetValue" : {
            "put" : {
                "description": "Atualiza o valor total da meta desejada",
                "tags":["Goals"],
                "security": [ {"bearerAuth": [] }],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref": "#/components/schemas/UpdateTotalValueGoal"
                            }
                        },
                        "examples":{
                            "UpdateTotalValueGoal":{
                                "value":{
                                    "goalId": "6122c3a5b005a50216500f16",
                                    "valor" : 1000
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "O valor não pode ser negativo ou zero !"
                    },
                    "200": {
                        "description" : "Valor da meta atualizado com sucesso !"
                    }
                }
            }
        },
        "/goals/RemoveValue" : {
            "post" : {
                "description" : "Remove o valor desejado da meta e adiciona a conta corrente do usuário",
                "tags":["Goals"],
                "security": [ {"bearerAuth": [] }],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref": "#/components/schemas/RemoveValueGoal"
                            }
                        },
                        "examples":{
                            "RemoveValueGoal":{
                                "value":{
                                    "goalId": "6122c3a5b005a50216500f16",
                                    "userId": "6123830a13e23200165885a4",
                                    "valor" : 1000
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "O valor a ser retirado da meta excede o valor diponível favor verificar o dado digitado !"
                    },
                    "200": {
                        "description" : "Valor removido da meta com sucesso !"
                    }
                }
            }
        },
        "/goals/NewGoal" : {
            "post" : {
                "description" : "Adiciona uma nova meta ao usuário",
                "tags" : ["Goals"],
                "security": [ {"bearerAuth": [] }],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" :  "#/components/schemas/NewGoal"
                            }
                        },
                        "examples":{
                            "NewGoal":{
                                "value":{
                                    "parentId": "6122c3a5b005a50216500f16",
                                    "parentName": "@teste",
                                    "nameGoal": "Comprar Celular",
                                    "valor" : 1000
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Usuário não encontrado na base de dados !"
                    }
                }
            }
        },
        "/goals/DeleteGoal" : {
            "delete" : {
                "description" : "Deleta a meta do usuário",
                "tags" : ["Goals"],
                "security": [ {"bearerAuth": [] }],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" :  "#/components/schemas/DeleteGoal"
                            }
                        },
                        "examples":{
                            "DeleteGoal":{
                                "value":{
                                    "_id": "6122c3a5b005a50216500f16"
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Meta não encontrada na base de dados !"
                    },
                    "200": {
                        "description" : "Meta excluída com sucesso"
                    }
                }
            }
        },
        "/goals/GetGoalsUser/{userId}" : {
            "get": {
                "description": "Busca a lista de metas do usuário",
                "tags": ["Goals"],
                "security": [ {"bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Usuário não encontrado na base de dados !"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ListGoals"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/goals/TransferToGoal" : {
            "put" : {
                "description": "Atualiza a meta com transferência da conta corrente do usuário",
                "tags":["Goals"],
                "security": [ {"bearerAuth": [] }],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref": "#/components/schemas/TransferToGoal"
                            }
                        },
                        "examples":{
                            "TransferToGoal":{
                                "value":{
                                    "_id": "5fac5938cf15b30027a003f3",
                                    "valor" : 1000,
                                    "conta": "254514"
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Saldo insuficiente para executar a ação !"
                    },
                    "200": {
                        "description" : "Transferência efetuada com sucesso !"
                    }
                }
            }
        },
        "/stocks/GetUserStocks/{userId}" : {
            "get" : {
                "description": "Busca a lista de investimento do usuário",
                "tags": ["ClientStocks"],
                "security": [ {"bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "Não encontrado nenhum investimento na base de dados !"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "type" : "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ListUserStocks"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/stocks/PostStockUserAccount" : {
           "post": {
            "description": "Realiza a compra das ações utilizando o saldo da conta corrente do usuário",
            "tags":["ClientStocks"],
            "security": [ {"bearerAuth": [] }],
            "requestBody" : {
                "content" : {
                    "application/json" : {
                        "schema":{
                            "$ref": "#/components/schemas/NewStockUser"
                         },
                         "examples":{
                            "NewStockUser":{
                                "value":{
                                    "parentId": "5f5d2dfdb2f39e0c743163a9",
                                    "stockId" : "608db860edc9160017d21f",
                                    "stockQtd" : 10
                                }
                            }
                        }
                    }
                }
              },
              "responses":{
                "401": {
                    "description": "Unauthorized"
                },
                "400":{
                    "description": "A quantidade solicitada para compra excede a quantidade disponível de stocks"
                },
                "200": {
                    "description": "Valor retirado da conta corrente para o investimento, efetuado com sucesso !"
                }
           }
        }
        },
        "/stocks/PostStockUserGoal" : {
            "post" : {
                "description": "Realiza a compra das ações utilizando o a meta escolhida pelo usuário",
                "tags":["ClientStocks"],
                "security": [ {"bearerAuth": [] }],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema":{
                                "$ref": "#/components/schemas/NewStockUserGoal"
                             },
                             "examples":{
                                "NewStockUserGoal":{
                                    "value":{
                                        "goalId" : "5fadcc07807878f50176994b3",
                                        "parentId": "5f5d2dfdb2f39e0c743163a9",
                                        "stockId" : "608db860edc9160017d21f",
                                        "stockQtd" : 10
                                    }
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400":{
                        "description": "A quantidade solicitada para compra excede a quantidade disponível de stocks"
                    },
                    "200": {
                        "description": "Valor retirado da meta para o investimento, efetuado com sucesso !"
                    }
                }
            }
        }
    },
    "components":{
        "schemas":{
            "Transferencia":{
                "type": "object",
                "properties": {
                    "conta":{
                        "type": "string"
                    },
                    "contaDestino":{
                        "type": "string"
                    },
                    "valor":{
                        "type": "string"
                    }
                }
            },
            "NewExpense": {
                "type": "object",
                "properties": {
                    "parentId": {
                        "type": "string"
                    },
                    "parentName": {
                        "type": "string"
                    },
                    "valor": {
                        "type": "number",
                        "multipleOf": 0.01
                    },
                    "data": {
                        "type": "string"
                    },
                    "categoria": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    }
                }
            },
            "ListExpenses": {
                "type": "object",
                "properties": {
                    "_id":{
                        "type": "string"
                    },
                    "parentId":{
                        "type": "string"
                    },
                    "parentName":{
                        "type": "string"
                    },
                    "valor":{
                        "type": "number",
                        "multipleOf": 0.01
                    },
                    "data":{
                        "type": "string"
                    },
                    "categoria":{
                        "type": "string"
                    },
                    "descricao":{
                        "type": "string"
                    }
                }
            },
            "login": {
                "type": "object",
                "properties": {
                    "_id":{
                        "type": "string"
                    },
                    "parentId":{
                        "type": "string"
                    },
                    "parentName":{
                        "type": "string"
                    },
                    "valor":{
                        "type": "decimal"
                    },
                    "data":{
                        "type": "string"
                    },
                    "categoria":{
                        "type": "string"
                    },
                    "descricao":{
                        "type": "string"
                    }
                }
            },
            "loginError":{
                "type": "object",
                "properties": {
                    "errorMsg":{
                        "type":"string",
                        "example" : "O usuário inicial não pode ser o mesmo de destino, favor verificar o dado digitado !"
                    }
                }
            },
            "UpdateTotalValueGoal": {
                "type": "object",
                "properties": {
                    "goalId": {
                        "type": "string"
                    },
                    "valor": {
                        "type": "number",
                        "multipleOf": 0.01
                    }
                }
            },
            "RemoveValueGoal" : {
                "type" : "object",
                "properties" : {
                    "goalId" : {
                        "type" : "string"
                    },
                    "userId" : {
                        "type" : "string"
                    },
                    "valor": {
                        "type": "number",
                        "multipleOf": 0.01
                    }
                }
            },
            "NewGoal" : {
                "type" : "object",
                "properties" : {
                    "parentId" : {
                        "type" : "string"
                    },
                    "parentName" : {
                        "type" : "string"
                    },
                    "nameGoal" : {
                        "type" : "string"
                    },
                    "valueGoal": {
                        "type": "number",
                        "multipleOf": 0.01
                    }
                }
            },
            "DeleteGoal" : {
                "type" : "object",
                "properties" : {
                    "_id" : {
                        "type" : "string"
                    }
                }
            },
            "ListGoals" : {
                "type": "object",
                "properties": {
                    "_id":{
                        "type": "string"
                    },
                    "parentId":{
                        "type": "string"
                    },
                    "parentName":{
                        "type": "string"
                    },
                    "nameGoal":{
                        "type": "string"
                    },
                    "valueGoal":{
                        "type": "number",
                        "multipleOf": 0.01
                    },
                    "currentGoalValue":{
                        "type": "number",
                        "multipleOf": 0.01
                    }
                }
            },
            "TransferToGoal" : {
                "type": "object",
                "properties": {
                    "_id":{
                        "type": "string"
                    },
                    "value":{
                        "type": "number",
                        "multipleOf": 0.01
                    },
                    "conta":{
                        "type": "string"
                    }
                }
            },
            "User" : {
                "type": "object",
                "properties": {
                    "_id":{
                        "type": "string"
                    },
                    "name":{
                        "type": "string"
                    },
                    "filterName":{
                        "type": "string"
                    },
                    "cpf":{
                        "type": "string"
                    },
                    "email":{
                        "type": "string"
                    },
                    "agencia":{
                        "type": "string"
                    },
                    "conta":{
                        "type": "string"
                    },
                    "saldo":{
                        "type": "number",
                        "multipleOf": 0.01
                    }
                }
            },
            "NewAccount" : {
                "type": "object",
                "properties": {
                    "name":{
                        "type": "string"
                    },
                    "userFilter":{
                        "type": "string"
                    },
                    "senha":{
                        "type": "string"
                    },
                    "cpf":{
                        "type": "string"
                    },
                    "email":{
                        "type": "string"
                    }
                }
            },
            "ResetPassword" : {
                "type" : "object",
                "properties" : {
                    "user" : {
                        "type" : "string"
                    } 
                }
            },
            "NewPassword" : {
                "type" : "object",
                "properties" : {
                    "email" : {
                        "type" : "string"
                    },
                    "senha" : {
                        "type" : "string"
                    },
                    "token" : {
                        "type" : "string"
                    } 
                }
            },
            "ListUserStocks" : {
                "type": "object",
                "properties": {
                    "_id":{
                        "type": "string"
                    },
                    "stockDisplayName":{
                        "type": "string"
                    },
                    "numberOfStocks":{
                        "type": "number"
                    },
                    "totalInvestment":{
                        "type": "number",
                        "multipleOf": 0.01
                    }
                }
            },
            "NewStockUser" : {
                "type" : "object",
                "properties" : {
                    "parentId" : {
                        "type" : "string"
                    },
                    "stockId" : {
                        "type" : "string"
                    },
                    "stockQtd" : {
                        "type" : "number"
                    }
                }
            },
            "NewStockUserGoal" : {
                "type" : "object",
                "properties" : {
                    "goalId" : {
                        "type" : "string"
                    },
                    "parentId" : {
                        "type" : "string"
                    },
                    "stockId" : {
                        "type" : "string"
                    },
                    "stockQtd" : {
                        "type" : "number"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}